
    create table asset_assignment_history (
        asset_id bigint not null,
        changed_at timestamp(6) with time zone not null,
        changed_by_user_id bigint not null,
        from_user_id bigint,
        id bigint generated by default as identity,
        to_user_id bigint,
        primary key (id)
    );

    create table asset_status_history (
        asset_id bigint not null,
        changed_at timestamp(6) not null,
        changed_by_user_id bigint not null,
        id bigint generated by default as identity,
        new_status varchar(255) not null check (new_status in ('AVAILABLE','ASSIGNED','IN_TRANSFER','IN_MAINTENANCE','UNAVAILABLE','RETIRED')),
        previous_status varchar(255) not null check (previous_status in ('AVAILABLE','ASSIGNED','IN_TRANSFER','IN_MAINTENANCE','UNAVAILABLE','RETIRED')),
        primary key (id)
    );

    create table assets (
        id bigint generated by default as identity,
        organization_id bigint not null,
        unit_id bigint not null,
        user_id bigint,
        version bigint not null,
        asset_tag varchar(255) not null unique,
        model varchar(255) not null,
        status varchar(255) not null check (status in ('AVAILABLE','ASSIGNED','IN_TRANSFER','IN_MAINTENANCE','UNAVAILABLE','RETIRED')),
        type varchar(255) not null check (type in ('MOBILE_PHONE','NOTEBOOK','TABLET','DESKTOP','VEHICLE','OTHER')),
        primary key (id)
    );

    create table audit_events (
        actor_user_id bigint,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        organization_id bigint not null,
        target_id bigint,
        unit_id bigint,
        target_type varchar(100),
        details TEXT,
        type varchar(255) not null check (type in ('ORGANIZATION_CREATED','ORGANIZATION_STATUS_CHANGED','ORGANIZATION_UPDATED','ORGANIZATION_ACTIVATED','ORGANIZATION_INACTIVATED','UNIT_CREATED','UNIT_STATUS_CHANGED','UNIT_UPDATED','UNIT_ACTIVATED','UNIT_INACTIVATED','USER_CREATED','USER_STATUS_CHANGED','USER_LGPD_ACCEPTED','USER_UPDATED','USER_ACTIVATED','USER_INACTIVATED','ASSET_CREATED','ASSET_ASSIGNED','ASSET_UNASSIGNED','ASSET_TRANSFERRED','ASSET_STATUS_CHANGED','ASSET_RETIRED','ASSET_UPDATED')),
        primary key (id)
    );

    create table inventory_items (
        present boolean not null,
        asset_id bigint not null,
        id bigint generated by default as identity,
        session_id bigint not null,
        primary key (id),
        constraint uk_inventory_session_asset unique (session_id, asset_id)
    );

    create table inventory_sessions (
        closed_at timestamp(6),
        created_at timestamp(6) not null,
        created_by bigint not null,
        id bigint generated by default as identity,
        organization_id bigint not null,
        unit_id bigint not null,
        version bigint not null,
        status varchar(255) not null check (status in ('OPEN','IN_PROGRESS','CLOSED','CANCELLED')),
        primary key (id)
    );

    create table maintenance_records (
        asset_id bigint not null,
        completed_at timestamp(6) with time zone,
        completed_by_user_id bigint,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        organization_id bigint not null,
        requested_by_user_id bigint not null,
        started_at timestamp(6) with time zone,
        started_by_user_id bigint,
        unit_id bigint not null,
        version bigint not null,
        description TEXT not null,
        resolution TEXT,
        status varchar(255) not null check (status in ('REQUESTED','IN_PROGRESS','COMPLETED','CANCELLED')),
        primary key (id)
    );

    create table organizations (
        id bigint generated by default as identity,
        status varchar(20) not null check (status in ('ACTIVE','INACTIVE')),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table transfer_requests (
        approved_at timestamp(6),
        approved_by bigint,
        asset_id bigint not null,
        completed_at timestamp(6),
        from_unit_id bigint not null,
        id bigint generated by default as identity,
        requested_at timestamp(6) not null,
        requested_by bigint not null,
        to_unit_id bigint not null,
        version bigint not null,
        status varchar(30) not null check (status in ('PENDING','APPROVED','REJECTED','COMPLETED','CANCELLED')),
        reason varchar(500) not null,
        primary key (id)
    );

    create table units (
        is_main boolean not null,
        id bigint generated by default as identity,
        organization_id bigint not null,
        status varchar(20) not null check (status in ('ACTIVE','INACTIVE')),
        name varchar(255) not null,
        primary key (id)
    );

    create table user_activation_tokens (
        used boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        token varchar(100) not null unique,
        primary key (id)
    );

    create table user_consents (
        lgpd_accepted boolean not null,
        accepted_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        primary key (id)
    );

    create table users (
        lgpd_accepted boolean not null,
        id bigint generated by default as identity,
        organization_id bigint not null,
        unit_id bigint not null,
        version bigint not null,
        document_number varchar(50) not null,
        role varchar(50) not null check (role in ('ADMIN','GESTOR','OPERADOR')),
        status varchar(50) not null check (status in ('PENDING_ACTIVATION','ACTIVE','BLOCKED','INACTIVE')),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        primary key (id)
    );

    create index idx_audit_org 
       on audit_events (organization_id);

    create index idx_audit_actor 
       on audit_events (actor_user_id);

    create index idx_audit_target 
       on audit_events (target_id);

    create index idx_audit_created_at 
       on audit_events (created_at);

    create index idx_audit_type 
       on audit_events (type);

    create index idx_inventory_item_session 
       on inventory_items (session_id);

    create index idx_inventory_item_asset 
       on inventory_items (asset_id);

    create index idx_inventory_session_org 
       on inventory_sessions (organization_id);

    create index idx_inventory_session_unit 
       on inventory_sessions (unit_id);

    create index idx_inventory_session_status 
       on inventory_sessions (status);

    create index idx_maintenance_asset 
       on maintenance_records (asset_id);

    create index idx_maintenance_org 
       on maintenance_records (organization_id);

    create index idx_maintenance_status 
       on maintenance_records (status);

    alter table if exists assets 
       add constraint FKi37wgdksbwub2fd1g8orrh975 
       foreign key (user_id) 
       references users;

    alter table if exists assets 
       add constraint FKgqxc5up08htqakpryiaod3ujs 
       foreign key (organization_id) 
       references organizations;

    alter table if exists assets 
       add constraint FKhw0fyx6bf4c907lgsksy86vix 
       foreign key (unit_id) 
       references units;

    alter table if exists inventory_items 
       add constraint FKkg7jexwtdc1ndrh5rffkc2e39 
       foreign key (asset_id) 
       references assets;

    alter table if exists inventory_items 
       add constraint FKiqbpoogrouq26yw5fhqjx59jw 
       foreign key (session_id) 
       references inventory_sessions;

    alter table if exists inventory_sessions 
       add constraint FK10xefx40fb9ths30upadsd7b3 
       foreign key (created_by) 
       references users;

    alter table if exists inventory_sessions 
       add constraint FKmc3t60rxg9lpya5tlx6drg8ea 
       foreign key (organization_id) 
       references organizations;

    alter table if exists inventory_sessions 
       add constraint FK3ymvgn6pb0pwqd9ho33n9pa5t 
       foreign key (unit_id) 
       references units;

    alter table if exists maintenance_records 
       add constraint FK124fjg43i0s5luwopsoq78k9h 
       foreign key (asset_id) 
       references assets;

    alter table if exists transfer_requests 
       add constraint FKr9lol8x40lsy5g7pgot27rc9i 
       foreign key (approved_by) 
       references users;

    alter table if exists transfer_requests 
       add constraint FKh7lp26n09l4kppiodawcfqtn3 
       foreign key (asset_id) 
       references assets;

    alter table if exists transfer_requests 
       add constraint FK4h44hvojk5yaqj12lkqd2g4r3 
       foreign key (from_unit_id) 
       references units;

    alter table if exists transfer_requests 
       add constraint FKa8k9c199befjiccignbbup4oq 
       foreign key (requested_by) 
       references users;

    alter table if exists transfer_requests 
       add constraint FKgmm8r1l1ru8jc9q8pkc4uvdy0 
       foreign key (to_unit_id) 
       references units;

    alter table if exists units 
       add constraint FKikrjcta3kxqs8scto8s6t4wv0 
       foreign key (organization_id) 
       references organizations;

    alter table if exists user_activation_tokens 
       add constraint FKn3ecsoid6jap5yyfk5llb2s06 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKqpugllwvyv37klq7ft9m8aqxk 
       foreign key (organization_id) 
       references organizations;

    alter table if exists users 
       add constraint FKp2hfld4bhbwtakwrmt4xq6een 
       foreign key (unit_id) 
       references units;
