server:
  port: 8080

spring:
  application:
    name: asset-management

  datasource:
    url: jdbc:postgresql://localhost:5433/asset_management
    username: asset_user
    password: asset123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
