-- =========================================
-- ASSET ASSIGNMENT HISTORY
-- =========================================
create table asset_assignment_history (
    id bigint generated by default as identity primary key,
    asset_id bigint not null,
    from_user_id bigint,
    to_user_id bigint,
    changed_by_user_id bigint not null,
    changed_at timestamp with time zone not null
);

alter table asset_assignment_history
add constraint fk_assignment_history_asset
foreign key (asset_id)
references assets(id);

alter table asset_assignment_history
add constraint fk_assignment_history_from_user
foreign key (from_user_id)
references users(id);

alter table asset_assignment_history
add constraint fk_assignment_history_to_user
foreign key (to_user_id)
references users(id);

alter table asset_assignment_history
add constraint fk_assignment_history_changed_by
foreign key (changed_by_user_id)
references users(id);

create index idx_assignment_history_asset on asset_assignment_history(asset_id);
create index idx_assignment_history_changed_at on asset_assignment_history(changed_at);

-- =========================================
-- ASSET STATUS HISTORY
-- =========================================
create table asset_status_history (
    id bigint generated by default as identity primary key,
    asset_id bigint not null,
    previous_status varchar(50) not null,
    new_status varchar(50) not null,
    changed_by_user_id bigint not null,
    changed_at timestamp with time zone not null
);

alter table asset_status_history
add constraint fk_status_history_asset
foreign key (asset_id)
references assets(id);

alter table asset_status_history
add constraint fk_status_history_changed_by
foreign key (changed_by_user_id)
references users(id);

create index idx_status_history_asset on asset_status_history(asset_id);
create index idx_status_history_changed_at on asset_status_history(changed_at);