-- C1: Tabela asset_categories ausente — entidade existe mas não havia migration.
-- Sem esta migration a aplicação falha no startup com ddl-auto: validate.

create table asset_categories (
    id          bigint generated by default as identity primary key,
    version     bigint not null default 0,
    name        varchar(100) not null,
    description varchar(255),
    active      boolean not null default true
);

alter table asset_categories
    add constraint uk_category_name unique (name);