-- =========================================================
-- V5: WhatsApp MFA — telefone nos usuários + tabela de OTPs
-- =========================================================

-- ─────────────────────────────────────────
-- Coluna phone_number na tabela users
-- Nullable — usuários sem telefone não passam por MFA
-- ─────────────────────────────────────────
alter table users
    add column if not exists phone_number varchar(20);

-- ─────────────────────────────────────────
-- Tabela de códigos MFA (OTP 6 dígitos via WhatsApp)
-- Cada código é de uso único e expira em 5 minutos (padrão)
-- ─────────────────────────────────────────
create table if not exists mfa_codes (
    id          bigint generated by default as identity primary key,
    user_id     bigint      not null,
    code        varchar(10) not null,
    used        boolean     not null default false,
    expires_at  timestamp with time zone not null,
    created_at  timestamp with time zone not null,
    constraint fk_mfa_user foreign key (user_id) references users(id)
);

create index if not exists idx_mfa_user    on mfa_codes(user_id);
create index if not exists idx_mfa_expiry  on mfa_codes(expires_at);