-- =========================================================
-- V6: Rate Limiting + Refresh Tokens
-- =========================================================

-- ─────────────────────────────────────────
-- Refresh tokens (para renovação de JWT sem relogin)
-- ─────────────────────────────────────────
create table if not exists refresh_tokens (
    id            bigint generated by default as identity primary key,
    user_id       bigint       not null,
    token         varchar(255) not null unique,
    expires_at    timestamp with time zone not null,
    revoked       boolean      not null default false,
    created_at    timestamp with time zone not null,
    constraint fk_refresh_user foreign key (user_id) references users(id)
);

create index if not exists idx_refresh_token  on refresh_tokens(token);
create index if not exists idx_refresh_user   on refresh_tokens(user_id);
create index if not exists idx_refresh_expiry on refresh_tokens(expires_at);

-- ─────────────────────────────────────────
-- Custo de manutenção 
-- ─────────────────────────────────────────
alter table maintenance_records
    add column if not exists estimated_cost numeric(15,2),
    add column if not exists actual_cost    numeric(15,2);

-- ─────────────────────────────────────────
-- Nota fiscal e garantia em assets (rastreabilidade fiscal)
-- ─────────────────────────────────────────
alter table assets
    add column if not exists purchase_date      date,
    add column if not exists invoice_number     varchar(100),
    add column if not exists invoice_date       date,
    add column if not exists supplier           varchar(255),
    add column if not exists warranty_expiry    date;
