-- =========================================================
-- V7: Features Financeiras
-- =========================================================

-- ─────────────────────────────────────────
-- Depreciação de ativos
-- ─────────────────────────────────────────
alter table assets
    add column if not exists purchase_value      numeric(15,2),
    add column if not exists residual_value      numeric(15,2) default 0,
    add column if not exists useful_life_months  int,
    add column if not exists depreciation_method varchar(30)
        check (depreciation_method in ('LINEAR','DECLINING_BALANCE','SUM_OF_YEARS'));

-- ─────────────────────────────────────────
-- Centro de custo
-- ─────────────────────────────────────────
create table if not exists cost_centers (
    id              bigint generated by default as identity primary key,
    organization_id bigint       not null,
    unit_id         bigint,
    code            varchar(50)  not null,
    name            varchar(255) not null,
    active          boolean      not null default true,
    constraint fk_cc_org  foreign key (organization_id) references organizations(id),
    constraint fk_cc_unit foreign key (unit_id)         references units(id),
    constraint uq_cc_code unique (organization_id, code)
);

create index if not exists idx_cc_org on cost_centers(organization_id);

alter table assets
    add column if not exists cost_center_id bigint,
    add constraint fk_asset_cc foreign key (cost_center_id) references cost_centers(id);

alter table maintenance_records
    add column if not exists cost_center_id bigint,
    add constraint fk_maint_cc foreign key (cost_center_id) references cost_centers(id);

-- ─────────────────────────────────────────
-- Seguro de ativos
-- ─────────────────────────────────────────
create table if not exists asset_insurance (
    id              bigint generated by default as identity primary key,
    asset_id        bigint        not null,
    organization_id bigint        not null,
    policy_number   varchar(100)  not null,
    insurer         varchar(255)  not null,
    coverage_value  numeric(15,2) not null,
    premium         numeric(15,2),
    start_date      date          not null,
    expiry_date     date          not null,
    active          boolean       not null default true,
    created_at      timestamp with time zone not null,
    constraint fk_ins_asset foreign key (asset_id)        references assets(id),
    constraint fk_ins_org   foreign key (organization_id) references organizations(id)
);

create index if not exists idx_ins_asset   on asset_insurance(asset_id);
create index if not exists idx_ins_expiry  on asset_insurance(expiry_date);
create index if not exists idx_ins_org     on asset_insurance(organization_id);
