-- =========================================
-- ORGANIZATIONS
-- =========================================
create table organizations (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    status varchar(20) not null
        check (status in ('ACTIVE','INACTIVE'))
);

-- =========================================
-- UNITS
-- =========================================
create table units (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    name varchar(255) not null,
    is_main boolean not null,
    status varchar(20) not null
        check (status in ('ACTIVE','INACTIVE'))
);

alter table units
add constraint fk_unit_org
foreign key (organization_id)
references organizations(id);

-- =========================================
-- USERS
-- =========================================
create table users (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    unit_id bigint not null,
    version bigint not null,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    document_number varchar(50) not null,
    role varchar(50) not null
        check (role in ('ADMIN','GESTOR','OPERADOR')),
    status varchar(50) not null
        check (status in ('PENDING_ACTIVATION','ACTIVE','BLOCKED','INACTIVE')),
    lgpd_accepted boolean not null
);

alter table users
add constraint fk_user_org
foreign key (organization_id)
references organizations(id);

alter table users
add constraint fk_user_unit
foreign key (unit_id)
references units(id);

-- =========================================
-- ASSETS
-- =========================================
create table assets (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    unit_id bigint not null,
    user_id bigint,
    version bigint not null,
    asset_tag varchar(255) not null unique,
    model varchar(255) not null,
    type varchar(255) not null
        check (type in ('MOBILE_PHONE','NOTEBOOK','TABLET','DESKTOP','VEHICLE','OTHER')),
    status varchar(255) not null
        check (status in ('AVAILABLE','ASSIGNED','IN_TRANSFER','IN_MAINTENANCE','UNAVAILABLE','RETIRED'))
);

alter table assets
add constraint fk_asset_org
foreign key (organization_id)
references organizations(id);

alter table assets
add constraint fk_asset_unit
foreign key (unit_id)
references units(id);

alter table assets
add constraint fk_asset_user
foreign key (user_id)
references users(id);

-- =========================================
-- AUDIT EVENTS
-- =========================================
create table audit_events (
    id bigint generated by default as identity primary key,
    type varchar(255) not null,
    actor_user_id bigint,
    organization_id bigint not null,
    unit_id bigint,
    target_id bigint,
    target_type varchar(100),
    details text,
    created_at timestamp with time zone not null
);

create index idx_audit_org on audit_events(organization_id);
create index idx_audit_actor on audit_events(actor_user_id);
create index idx_audit_target on audit_events(target_id);
create index idx_audit_created_at on audit_events(created_at);
create index idx_audit_type on audit_events(type);

-- =========================================
-- INVENTORY SESSIONS
-- =========================================
create table inventory_sessions (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    unit_id bigint not null,
    created_by bigint not null,
    version bigint not null,
    created_at timestamp not null,
    closed_at timestamp,
    status varchar(255) not null
        check (status in ('OPEN','IN_PROGRESS','CLOSED','CANCELLED'))
);

alter table inventory_sessions
add constraint fk_inventory_session_org
foreign key (organization_id)
references organizations(id);

alter table inventory_sessions
add constraint fk_inventory_session_unit
foreign key (unit_id)
references units(id);

alter table inventory_sessions
add constraint fk_inventory_session_user
foreign key (created_by)
references users(id);

create index idx_inventory_session_org on inventory_sessions(organization_id);
create index idx_inventory_session_unit on inventory_sessions(unit_id);
create index idx_inventory_session_status on inventory_sessions(status);

-- =========================================
-- INVENTORY ITEMS
-- =========================================
create table inventory_items (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    asset_id bigint not null,
    present boolean not null,
    constraint uk_inventory_session_asset
        unique(session_id, asset_id)
);

alter table inventory_items
add constraint fk_inventory_item_session
foreign key (session_id)
references inventory_sessions(id);

alter table inventory_items
add constraint fk_inventory_item_asset
foreign key (asset_id)
references assets(id);

create index idx_inventory_item_session on inventory_items(session_id);
create index idx_inventory_item_asset on inventory_items(asset_id);

-- =========================================
-- MAINTENANCE
-- =========================================
create table maintenance_records (
    id bigint generated by default as identity primary key,
    asset_id bigint not null,
    organization_id bigint not null,
    unit_id bigint not null,
    requested_by_user_id bigint not null,
    started_by_user_id bigint,
    completed_by_user_id bigint,
    version bigint not null,
    description text not null,
    resolution text,
    created_at timestamp with time zone not null,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    status varchar(255) not null
        check (status in ('REQUESTED','IN_PROGRESS','COMPLETED','CANCELLED'))
);

alter table maintenance_records
add constraint fk_maintenance_asset
foreign key (asset_id)
references assets(id);

create index idx_maintenance_asset on maintenance_records(asset_id);
create index idx_maintenance_org on maintenance_records(organization_id);
create index idx_maintenance_status on maintenance_records(status);

-- =========================================
-- TRANSFER REQUESTS
-- =========================================
create table transfer_requests (
    id bigint generated by default as identity primary key,
    asset_id bigint not null,
    from_unit_id bigint not null,
    to_unit_id bigint not null,
    requested_by bigint not null,
    approved_by bigint,
    version bigint not null,
    requested_at timestamp not null,
    approved_at timestamp,
    completed_at timestamp,
    reason varchar(500) not null,
    status varchar(30) not null
        check (status in ('PENDING','APPROVED','REJECTED','COMPLETED','CANCELLED'))
);

alter table transfer_requests
add constraint fk_transfer_asset
foreign key (asset_id)
references assets(id);

alter table transfer_requests
add constraint fk_transfer_from_unit
foreign key (from_unit_id)
references units(id);

alter table transfer_requests
add constraint fk_transfer_to_unit
foreign key (to_unit_id)
references units(id);

alter table transfer_requests
add constraint fk_transfer_requested_by
foreign key (requested_by)
references users(id);

alter table transfer_requests
add constraint fk_transfer_approved_by
foreign key (approved_by)
references users(id);

-- =========================================
-- USER CONSENTS
-- =========================================
create table user_consents (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    lgpd_accepted boolean not null,
    accepted_at timestamp not null
);

alter table user_consents
add constraint fk_user_consents_user
foreign key (user_id)
references users(id);

-- =========================================
-- USER ACTIVATION TOKENS
-- =========================================
create table user_activation_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(100) not null unique,
    used boolean not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null
);

alter table user_activation_tokens
add constraint fk_user_activation_token_user
foreign key (user_id)
references users(id);
